#!/usr/bin/env python3
import subprocess
import sys

import pkg_resources


def is_installed(package_name):
    """Check if a package is already installed."""
    try:
        pkg_resources.get_distribution(package_name)
        return True
    except pkg_resources.DistributionNotFound:
        return False


def install_package(package_name):
    """Install the package using pip if not already installed."""
    if is_installed(package_name):
        print(
            f"[INFO] Package '{package_name}' is already installed. Skipping.")
    else:
        print(f"[INFO] Installing package '{package_name}'...")
        subprocess.check_call(
            [sys.executable, '-m', 'pip', 'install', package_name])


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python pip_wrapper.py <package1> <package2> ...')
        sys.exit(1)

    for pkg in sys.argv[1:]:
        install_package(pkg)
