#!/data/data/com.termux/files/usr/bin/env python3

import subprocess
import sys


def main() -> None:
    pip_cmd = [
        sys.executable,
        '-m',
        'pip',
        'download',
        '--no-deps',
        '--no-build-isolation',
        '--use-pep517=no',  # prevents metadata build
        '--dest',
        '.',
        str(sys.argv[1:]),
    ]

    subprocess.check_call(pip_cmd)


if __name__ == '__main__':
    main()
